In [10]:
import pandas as pd

df_from_dict = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'Имя': ['Иван', 'Ольга', 'Алексей', 'Мария', 'Сергей', 'Анна', 'Дмитрий', 'Елена', 'Виктор', 'Алиса',
            'Павел', 'Светлана', 'Роман', 'Татьяна', 'Николай', 'Валерия', 'Григорий', 'Юлия', 'Степан', 'Василиса'],
    'Возраст': [25, 30, 40, 35, 28, 32, 45, 29, 31, 27, 33, 26, 42, 37, 39, 24, 50, 45, 41, 38],
    'Должность': ['Инженер', 'Аналитик', 'Менеджер', 'Программист', 'Специалист', 'Разработчик', 'HR', 'Маркетолог', 'Юрист', 'Дизайнер',
                  'Администратор', 'Тестировщик', 'Финансист', 'Редактор', 'Логист', 'SEO-специалист', 'Бухгалтер', 'Директор', 'Экономист', 'Проект-менеджер'],
    'Отдел': ['ИТ', 'Маркетинг', 'Продажи', 'ИТ', 'HR', 'ИТ', 'HR', 'Маркетинг', 'Юридический', 'Дизайн', 'Администрация', 'Тестирование', 'Финансы', 'Редакция', 'Логистика', 'SEO', 'Финансы', 'Финансы', 'Продажи', 'Продажи'],
    'Зарплата': [60000, 75000, 90000, 80000, 50000, 85000, 48000, 70000, 95000, 62000, 55000, 67000, 105000, 72000, 75000, 64000, 110000, 150000, 98000, 88000],
    'Стаж работы': [2, 5, 15, 7, 3, 6, 12, 4, 10, 5, 7, 2, 20, 9, 11, 3, 25, 20, 14, 8]
})

#  Экспорт DataFrame в JSON файл
json_filename = 'employees.json'
df_from_dict.to_json(json_filename, orient='records', force_ascii=False)

#  JSON файл обратно в DataFrame
loaded_json_df = pd.read_json(json_filename, orient='records')

#  первые 5 строк
print(loaded_json_df.head())

   ID      Имя  Возраст    Должность      Отдел  Зарплата  Стаж работы
0   1     Иван       25      Инженер         ИТ     60000            2
1   2    Ольга       30     Аналитик  Маркетинг     75000            5
2   3  Алексей       40     Менеджер    Продажи     90000           15
3   4    Мария       35  Программист         ИТ     80000            7
4   5   Сергей       28   Специалист         HR     50000            3